name 'piksel-iis'
version '0.1.4'
summary 'IIS module. Configures app pools, sites, applications and virtual directories.'
description 'IIS module. Configures app pools, sites, applications and virtual directories.'
project_page 'https://github.com/pikselpalette/puppet-iis'
license 'Apache License, Version 2.0'
author 'piksel'
source 'https://github.com/pikselpalette/puppet-iis'
